export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
